import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const appRoot = path.resolve(import.meta.dirname, "..");
const workspaceRoot = path.resolve(appRoot, "../..");
const outputPath = path.join(appRoot, "generated", "env.js");

const defaults = {
  API_BASE_URL: "http://10.0.2.2:4000",
  API_TIMEOUT_MS: "10000"
};

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  const contents = fs.readFileSync(filePath, "utf8");
  const values = {};

  for (const rawLine of contents.split(/\r?\n/)) {
    const line = rawLine.trim();

    if (!line || line.startsWith("#")) {
      continue;
    }

    const separatorIndex = line.indexOf("=");

    if (separatorIndex === -1) {
      continue;
    }

    const key = line.slice(0, separatorIndex).trim();
    let value = line.slice(separatorIndex + 1).trim();

    if (
      (value.startsWith("\"") && value.endsWith("\"")) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    values[key] = value;
  }

  return values;
}

const fileEnv = {
  ...parseEnvFile(path.join(workspaceRoot, ".env")),
  ...parseEnvFile(path.join(appRoot, ".env"))
};

const env = {
  API_BASE_URL:
    process.env.API_BASE_URL ?? fileEnv.API_BASE_URL ?? defaults.API_BASE_URL,
  API_TIMEOUT_MS: Number(
    process.env.API_TIMEOUT_MS ?? fileEnv.API_TIMEOUT_MS ?? defaults.API_TIMEOUT_MS
  )
};

if (!Number.isFinite(env.API_TIMEOUT_MS)) {
  throw new Error("API_TIMEOUT_MS must be a number");
}

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(
  outputPath,
  `// This file is generated by scripts/generate-env.mjs.\n` +
    `// Edit .env instead of changing this file directly.\n` +
    `export const generatedEnv = ${JSON.stringify(env, null, 2)};\n`,
  "utf8"
);
